spring.application.name=inventory-service
server.port=8082

# SQL Server
spring.datasource.url=jdbc:sqlserver://${SQLSERVER_HOST:localhost}:1433;databaseName=inventory_service;encrypt=true;trustServerCertificate=true
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:LocalDev_Passw0rd}
spring.jpa.hibernate.ddl-auto=update

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}
eureka.instance.prefer-ip-address=${EUREKA_PREFER_IP_ADDRESS:false}

# Tracing
management.tracing.sampling.probability=1.0
management.tracing.export.zipkin.endpoint=${ZIPKIN_URL:http://localhost:9411/api/v2/spans}
